USE COMPANY;
SELECT * FROM COUNTRIES;
SELECT * FROM DEPENDENTS;
SELECT * FROM DEPARTMENT;
SELECT * FROM EMPLOYEES;
SELECT * FROM JOBS;


ALTER TABLE DEPTS RENAME TO DEPARTMENT;
ALTER TABLE REGIONS MODIFY COLUMN REGION_NAME VARCHAR(10);
ALTER TABLE REGIONS ADD COLUMN DEMO VARCHAR(10);
ALTER TABLE REGIONS DROP DEMO;
ALTER TABLE JOBS RENAME TO JOB;

SELECT COUNTRY_NAME FROM COUNTRIES WHERE REGION_ID=1;
SELECT * FROM COUNTRIES WHERE REGION_ID BETWEEN 1 AND 2;
SELECT COUNTRY_NAME FROM COUNTRIES WHERE NOT COUNTRY_NAME LIKE "C%";
SELECT * FROM COUNTRIES ORDER BY REGION_ID;

UPDATE EMPLOYEES SET COMMISSIONS=3000 WHERE DEPARTMENT_ID=11;
DELETE FROM EMPLOYEES WHERE EMPLOYEE_ID=209;

SELECT * FROM EMPLOYEES ORDER BY SALARY DESC LIMIT 3;
SELECT MIN(SALARY) FROM EMPLOYEES;
SELECT COUNT(EMPLOYEE_ID) AS COUNT_OF_EMPLOYEES FROM EMPLOYEES;

SELECT AVG(SALARY) FROM EMPLOYEES WHERE SALARY<10000;
SELECT AVG(SALARY) FROM EMPLOYEES GROUP BY JOB_ID;


ALTER TABLE EMPLOYEES MODIFY COLUMN SALARY INT;

SELECT FIRST_NAME FROM EMPLOYEES INNER JOIN JOBS ON EMPLOYEES.JOB_ID = JOBS.JOB_ID WHERE JOB_TITLE="Shipping Clerk";
SELECT * FROM EMPLOYEES WHERE year(HIRE_DATE) BETWEEN 1995 AND 1997;

SELECT lower(EMAIL) AS EMAIL FROM EMPLOYEES;

SELECT WEEKDAY(HIRE_DATE) FROM EMPLOYEES WHERE LAST_NAME="King";
SELECT dayname(HIRE_DATE) FROM EMPLOYEES WHERE LAST_NAME="King";

SELECT MAX(SALARY) FROM EMPLOYEES GROUP BY DEPARTMENT_ID;
select concat(first_name," ",last_name) as Employee_Name, hire_date from employees 
where dayname(hire_date)='Thursday';